repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
    exclude: ^testfiles\/
  - id: mixed-line-ending
    args: [--fix=no]
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    exclude: ^genutility\/tests\/markdown\.py$
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 2.1.4
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-use-type-annotations
- repo: https://github.com/asottile/pyupgrade
  rev: v3.16.0
  hooks:
  - id: pyupgrade
    args: [--py37-plus]
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.4.2
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.10
  hooks:
  - id: bandit
    args: [-c, pyproject.toml]
    additional_dependencies: ['.[toml]']
- repo: https://github.com/pycqa/flake8
  rev: 7.1.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-annotations
    - flake8-bugbear
    - flake8-eradicate
    - flake8-mutable
    - flake8-simplify
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
  - id: mypy
    args: [--install-types, --non-interactive, --show-error-codes, --show-traceback]
    additional_dependencies:
    - aiohttp==3.8.6
    - aria2p==0.11.3
    - av>=8.0
    - beautifulsoup4==4.13.3
    - bencode.py==4.0.0
    - cryptography==44.0.2
    - ctypes-windows-sdk==0.0.15; sys_platform=='win32'
    - Flask==2.2.5
    - gensim==4.2.0
    - gmpy2==2.2.1
    - hypothesis==6.79.4
    - jsonschema==4.17.3
    - lxml==5.3.1
    - mistune==3.0.2
    - msgpack==1.0.5
    - netifaces==0.11.0
    - networkx==2.6.3
    - nltk==3.8.1
    - numba==0.56.4
    - numpy==1.21.6
    - opencv-python==4.10.0.82
    - pandas==1.3.5
    - pdfminer==20191125
    - piexif==1.1.3
    - Pillow==9.5.0
    - polars==0.18.4
    - pymediainfo==6.1.0
    - pymongo==4.7.3
    - pyOpenSSL==24.3.0
    - pypdf==4.3.1
    - python-pptx==0.6.23
    - pywin32==308; sys_platform=='win32'       # win32evtlog, winerror
    - requests==2.31.0
    - rhash
    - ruamel.yaml==0.18.10
    - scipy==1.7.3
    - simple-salesforce==1.12.6
    - simplejson==3.20.1
    - sortedcontainers==2.4.0
    - tensorflow==2.11.0
    - tls-property==1.1.0
    - toml==0.10.2
    - twisted==23.8.0
    - typing-extensions==4.7.1
    - Unidecode==1.3.8
    - werkzeug==2.2.3
    - WMI==1.5.1; sys_platform=='win32'
    - wxasync==0.49
    - wxPython==4.1.1
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
