repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/PyCQA/isort
    rev: 5.5.4
    hooks:
      - id: isort
        language_version: python3
