repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: ['--ini', '.bandit']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.790'
    hooks:
      - id: mypy
        args: []
        additional_dependencies:
          - future
          - aria2p
          - aiohttp>=2.3
          - beautifulsoup4
          - bencode.py>=2.0.0
          - cryptography>=1.5.3
          - flask>=0.12.3
          - hypothesis
          - jsonschema
          - lxml
          - msgpack>=0.6.0
          - netifaces
          - networkx
          - nltk
          - numba
          - numpy
          - opencv-python
          - orderedset
          - piexif
          - pymongo
          - pillow
          - python-pptx
          - pymediainfo
          - PyPDF2
          - pyOpenSSL>=17.5.0
          - requests
          - rhash
          - ruamel.yaml
          - scipy
          - simple_salesforce>=1.1.0
          - simplejson
          - sortedcontainers
          - tls-property>=1.0.1
          - tensorflow
          - toml
          - twisted
          - unidecode
          - werkzeug>=0.11.11
          - wxPython
