repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.2.0'
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
        exclude: ^testfiles\/
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.32.1'
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
      - id: bandit
        args: ['--ini', '.bandit']
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.950'
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive", "--show-error-codes"]
        additional_dependencies:
          - aiohttp>=2.3
          - aria2p
          - beautifulsoup4
          - bencode.py>=2.0.0
          - cryptography>=1.5.3
          - ctypes-windows-sdk>=0.0.7; sys_platform=='win32'
          - flask>=0.12.3
          - gensim==4.1.2
          - hyper
          - hypothesis
          - jsonschema
          - lxml
          - msgpack>=0.6.0
          - netifaces
          - networkx
          - nltk
          - numba
          - numpy
          - opencv-python
          - orderedset
          - pandas
          - piexif
          - pillow
          - pymediainfo
          - pymongo
          - pyOpenSSL>=17.5.0
          - PyPDF2>=1.28.0
          - python-pptx
          - pywin32; sys_platform=='win32' # win32evtlog, winerror
          - requests
          - rhash
          - ruamel.yaml
          - scipy<1.6.0
          - simple_salesforce>=1.1.0
          - simplejson
          - sortedcontainers
          - tensorflow
          - tls-property>=1.0.1
          - toml
          - twisted
          - typing-extensions
          - unidecode
          - werkzeug>=0.11.11
          - wmi; sys_platform=='win32'
          - wxasync
          - wxPython>=4
