[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=66.1" ]

[project]
name = "genutility"
version = "0.0.123"
description = "A collection of various Python utilities"
readme = "README.md"
license = { file = "LICENSE" }
authors = [ { name = "Dobatymo" } ]
requires-python = ">=3.8"
classifiers = [
  "License :: OSI Approved :: ISC License (ISCL)",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
  "Topic :: Utilities",
]
dynamic = [
  "dependencies",
  "optional-dependencies",
]
urls.Homepage = "https://github.com/Dobatymo/genutility"

[dependency-groups]
dev = [
  "mypy>=1.14.1",
  "types-pyopenssl>=24.1.0.20240722",
  "types-requests>=2.32.0.20241016",
  "types-simplejson>=3.19.0.20241221",
  "types-toml>=0.10.8.20240310",
]

[tool.ruff]
line-length = 120
lint.extend-select = [ "B", "C4", "DTZ", "I", "PIE", "RUF", "S", "SIM", "UP" ]
lint.ignore = [ "B011", "S101", "SIM102", "SIM108" ]
lint.per-file-ignores = { "stubs/**/*.py" = [ "UP" ], "stubs/**/*.pyi" = [ "UP" ] }
lint.pyupgrade.keep-runtime-typing = true

[tool.mypy]
exclude = [ "build" ]
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
allow_redefinition = true
strict_equality = true
show_traceback = true
warn_unused_configs = true
no_implicit_optional = true
show_error_codes = true

[tool.pytest]
ini_options.testpaths = [
  "genutility/tests",
]
ini_options.python_files = [
  "*.py",
]
ini_options.log_level = "DEBUG"

[tool.coverage]
report.exclude_lines = [
  "if __name__ == .__main__.:",
  "pragma: no cover",
]
report.sort = "Cover"
